spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: Conmuaqua123

# JPA Settings
  jpa.hibernate.ddl_auto: create
  jpa.show-sql: true